### ISSUE TITLE
Tételszámok

### ISSUE THREAD

**Issue by klenium** [vista-/Bsz2-tetelek#13]
First world problem: 14 tételtől a tételek sorszáma a címnél 13.

**Comment by vista-** [comment]
nalam nem¯\_(ツ)_/¯ 
![http://static.notx.ml/u/a5377e66ce.png](http://static.notx.ml/u/a5377e66ce.png)

**Comment by klenium** [comment]
https://github.com/bme-vik/Bsz2-tetelek/blob/master/16_tetel.tex
\title{Bevezetés a Számításelméletbe 2.\{\large 13. tétel}}

**Comment by klenium** [comment]
Úgy látom, amit én néztem, úgy rakták össze, hogy a tételeket egyenként generálták le, majd valami pdf merge cuccal egyesítették, és mivel a különálló tétel forrásában rossz a szám, így nálam rossz. De amit te mutatsz, az egybe lett generálva, ott meg a full_document.tex beállításai érvényesek, ott jó a szám.
