### ISSUE TITLE
2. tétel: Izomorfia

### ISSUE THREAD

**Issue by balazsrev** [vista-/Bsz2-tetelek#18]
2. sorban az első vessző után hiányzik egy "h" betű

**Comment by vista-** [comment]
Koszonjuk a bekuldott issue-kat, amennyiben van idod es lehetoseged, akkor a kis hibak fixeit kuldd be egy pull request-ben. 

A rendszer direkt ugy van megcsinalva, hogy csak a forrast kelljen atirni es ne kelljen LaTeX-het letolteni/forditani, a forditast elvegzi helyetted a Travis CI.
