### ISSUE TITLE
Kindle layout

### ISSUE THREAD

**Issue by bokrosbalint** [vista-/Bsz2-tetelek#2]
A `\usepackage[a4paper,margin=2cm,footskip=.5cm]{geometry}`
sort erre `\usepackage[papersize={3.6in,4.8in},margin=0.1in]{geometry}` cserélve Kindle-ön (meg más 6'-os eBook readereken) egész jól használható verzió születik, ha gondolod beépítheted a shell scriptekbe, nekem a sed meg az awk egyelőre nagyon medzsik, szóval a pull request most kimarad

**Comment by vista-** [comment]
Csináltam egy Kindle-s teljes tételsor tex fájlt. és hozzáadtam a makefile-hoz: d4dc4d5
