### ISSUE TITLE
DFS-keresés: nem kell csökkenteni D-t

### ISSUE THREAD

**Issue by kuklinistvan** [vista-/Bsz2-tetelek#25]
Félreértettem azt a részét az algoritmusnak és sikerült átjavítanom. Itt is jelzem, hogy az valószínűleg nem jó.

**Comment by martonbognar** [comment]
Ha megtudod biztosan, hogy mi a helyzet, tudsz annak megfeleloen PR-t kuldeni/jelezni itt, hogy jo, ahogy most van?

**Comment by kuklinistvan** [comment]
Igen - valószínűleg késni fog, mert kicsit elvagyok havazva, de ha lesz biztos(abb) információ és eljutok odáig, feltétlenül.

**Comment by kuklinistvan** [comment]
Na, #28-ban javítottam, szerintem így már jó lesz.
