### ISSUE TITLE
Euler-kör másik irányának bizonyítása Szeszlér előadásáról

### ISSUE THREAD

**Issue by DanielSharp01** [vista-/Bsz2-tetelek#26]
A Szeszlér előadáson előkerülő bizonyítás, a [összefüggő gráf, páros fokszám => Euler-kör] feltételre a következő volt:

Az alábbi algoritmus szerint keressünk Euler-kört:

0. Vegyünk egy random 'v' csúcsot
1. Ebből a csúcsból elakadásig menjünk egy olyan élsorozaton, amelyben nincs élismétlés (egyfajta él-útat). Ekkor belátható, hogy ennek az élsorozatnak a 'v'-ben kell végződnie. Nem tudunk köztes pontban elakadni, mert minden csúcs amibe bemegyünk, abból ki is (páros fokszámokat itt használjuk ki). Speciálisan a kezdő csúcsból kifele haladás és befelé haladás a kör elejét és végét adja.
2. HA P már Euler-kör => STOP
3. HA nem akkor, létezik olyan 'w' csúcs a P úton, amely P-beli és nem P-beli éleket is tartalmaz. (Ha nem így lenne akkor nem összefüggő a gráf)
4. Alkalmazzuk belőle kiindulva egy olyan gráfra az algoritmust, amely E(G) \ E(P) élhalmazzal rendelkezik (és nyilván a tejlesen szaturált csúcsokat sem tartalmazza már). Ez ugyanúgy 'w'-ben fog elakadni a fentiek miatt.
5. Adjuk össze a két utat v -> w + Q élsorozat + w -> v ezt nevezzük P' élsorozatnak

Ha az algoritmuson belül is előfordul, hogy nem Euler-kört kapunk, akkor nyílván ott is kell egy köztes pontot keresni a fentieknek megfelelően. Ezt a rekurzív algoritmust alkalmazva végül Euler-kört kell kapjunk. Ennek belátásához, már csak az algoritmus lépésszámának végessége kell. Ami nyilvánvaló hisz E(P') > E(P), ez viszont nem tud E(G) felé nőni.

Az Euler-úthoz annyi a + trükk, hogy ha ez igaz, akkor a két kivételellel páros fokszámú gráfok két kivételét összekötve, olyan gráfot kapunk, amiben van Euler-kör. Hagyjuk el a plusz élet és van egy útunk.

Ha valaki magyaráz nekem LaTex-et, akkor szívesen leírom a jegyzetbe is, jelenleg nem nagyon értek hozzá.

**Comment by DanielSharp01** [comment]
Itt van egy jegyzet, amiben amúgy ez (pontosabban is) benne van:
http://www.cs.bme.hu/~fleiner/jegyzet/BSz2.1.5.pdf (7. oldal)

**Comment by kuklinistvan** [comment]
Nagyon köszönjük! :)

**Comment by DanielSharp01** [comment]
Összerektam ezt és egy másik bizonyítást: https://github.com/bme-notes/bsz2/pull/27

**Comment by martonbognar** [comment]
A merge alapjan akkor ezt is bezarhatom, ugye?
