### ISSUE TITLE
Feszítőfa

### ISSUE THREAD

**Issue by udvaritibor** [vista-/Bsz2-tetelek#9]
"Az F gráf a G gráf feszítőfája, ha F fa, és részgráfja G-nek."

Itt nem "feszítő részgráfja G-nek"?

**Comment by marazmarci** [comment]
De, bizony! A számítástudomány alapjai c. könyv alapján készült a jegyzet, aminek a hivatalos hibajegyzékében javították ezt az elírást:
http://www.cs.bme.hu/~kiskat/konyv/hibajegyzek.pdf
Már csináltam pull request-et

**Comment by vista-** [comment]
Fixed in commit 6109b68f3afcb1019c369ec9dcc6b1fcb52e4cd3
